# Generated by Django 5.2.4 on 2025-08-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_alter_messagelog_template_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelog',
            name='template_type',
            field=models.CharField(choices=[('initial', 'Initial'), ('followup1', '15-min Follow-up'), ('followup2', '1-hour Follow-up'), ('status_updated', 'Status Updated')], max_length=20),
        ),
    ]
