# Generated by Django 5.2.4 on 2025-09-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_alter_messagelog_template_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappsession',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
